// Build-time only. Samples an evenly spread set of points over the sphere,
// works out which country (if any) each one falls in, and writes the answer
// out as one byte per point. The page regenerates the coordinates from the
// same formula, so it never has to ship them — and never has to ship d3.
const fs = require("fs");
const topojson = require("topojson-client");
const { geoContains, geoBounds } = require("d3-geo");

const N = 24000;                    // points over the whole sphere
const OUT = "/Users/mitchellscholte/MISCSTUDIO/MISC-STUDIO/about-globe-data.js";

const topo = JSON.parse(fs.readFileSync(__dirname + "/countries-110m.json", "utf8"));
const fc = topojson.feature(topo, topo.objects.countries);
const countries = fc.features
  .filter(f => f.properties && f.properties.name)
  .map(f => ({ name: f.properties.name, feature: f, bounds: geoBounds(f) }));
console.log("countries:", countries.length);
if (countries.length > 254) throw new Error("too many countries for one byte");

// Fibonacci sphere — even coverage, no clumping at the poles the way a
// plain lon/lat grid does
function point(i) {
  const golden = Math.PI * (3 - Math.sqrt(5));
  const y = 1 - (i / (N - 1)) * 2;
  const r = Math.sqrt(Math.max(0, 1 - y * y));
  const th = golden * i;
  const lat = Math.asin(y) * 180 / Math.PI;
  const lon = Math.atan2(Math.sin(th) * r, Math.cos(th) * r) * 180 / Math.PI;
  return [lon, lat];
}

const OCEAN = 255;
const out = new Uint8Array(N).fill(OCEAN);
let land = 0;

for (let i = 0; i < N; i++) {
  const p = point(i);
  for (let c = 0; c < countries.length; c++) {
    const b = countries[c].bounds;               // [[w,s],[e,n]] — cheap reject first
    if (p[1] < b[0][1] || p[1] > b[1][1]) continue;
    const w = b[0][0], e = b[1][0];
    const inLon = w <= e ? (p[0] >= w && p[0] <= e) : (p[0] >= w || p[0] <= e);
    if (!inLon) continue;
    if (geoContains(countries[c].feature, p)) { out[i] = c; land++; break; }
  }
  if (i % 4000 === 0) process.stdout.write(".");
}
console.log("\nland points:", land, "of", N, "(" + Math.round(land / N * 100) + "%)");

const b64 = Buffer.from(out).toString("base64");
const js = `// GENERATED by tools/build-globe.js — do not edit by hand.
// One byte per sample point: the index of the country it falls in, or 255 for
// ocean. Coordinates are not stored; about-globe.js rebuilds them from the same
// Fibonacci formula, which is why this file is 30KB instead of 300KB.
window.GLOBE_DATA = {
  count: ${N},
  ocean: ${OCEAN},
  countries: ${JSON.stringify(countries.map(c => c.name))},
  bytes: "${b64}"
};
`;
fs.writeFileSync(OUT, js);
console.log("wrote", OUT, fs.statSync(OUT).size, "bytes");
